/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'description' : string,
  'timestamp' : Time,
  'actorPrincipal' : Principal,
}
export interface Bill {
  'tax' : Price,
  'order' : Order,
  'grandTotal' : Price,
  'subtotal' : Price,
}
export type ExternalBlob = Uint8Array;
export interface MenuCategory {
  'id' : MenuCategoryId,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
}
export type MenuCategoryId = bigint;
export interface MenuItem {
  'id' : MenuItemId,
  'categoryId' : MenuCategoryId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'isVeg' : boolean,
  'price' : Price,
}
export type MenuItemId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'staffId' : Principal,
  'createdAt' : Time,
  'tableId' : TableId,
  'updatedAt' : Time,
  'totalAmount' : Price,
  'notes' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'notes' : string,
  'quantity' : bigint,
  'price' : Price,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'served' : null } |
  { 'ready' : null };
export interface PlatformStats {
  'suspendedTenants' : bigint,
  'totalMonthlyRevenue' : bigint,
  'totalTenants' : bigint,
  'activeTenants' : bigint,
  'trialTenants' : bigint,
}
export type Price = bigint;
export interface RegisterTenantInput {
  'country' : string,
  'ownerName' : string,
  'city' : string,
  'businessName' : string,
  'email' : string,
  'phone' : string,
}
export interface RestaurantTable {
  'id' : TableId,
  'status' : TableStatus,
  'name' : string,
  'currentOrderId' : [] | [OrderId],
  'capacity' : bigint,
  'qrCode' : string,
}
export type TableId = bigint;
export interface TableInput {
  'name' : string,
  'capacity' : bigint,
  'qrCode' : string,
}
export type TableStatus = { 'occupied' : null } |
  { 'reserved' : null } |
  { 'available' : null };
export interface Tenant {
  'id' : bigint,
  'status' : TenantStatus,
  'country' : string,
  'outletCount' : bigint,
  'ownerName' : string,
  'city' : string,
  'plan' : TenantPlan,
  'joinedAt' : Time,
  'businessName' : string,
  'email' : string,
  'phone' : string,
  'monthlyRevenue' : bigint,
}
export interface TenantInput {
  'status' : TenantStatus,
  'country' : string,
  'outletCount' : bigint,
  'ownerName' : string,
  'city' : string,
  'plan' : TenantPlan,
  'businessName' : string,
  'email' : string,
  'phone' : string,
  'monthlyRevenue' : bigint,
}
export interface TenantNotification { 'unread' : boolean, 'tenant' : Tenant }
export type TenantPlan = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'starter' : null };
export type TenantStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'suspended' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateTenant' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string, bigint], MenuCategoryId>,
  'createMenuItem' : ActorMethod<
    [bigint, string, string, Price, [] | [ExternalBlob], boolean, boolean],
    MenuItemId
  >,
  'createOrder' : ActorMethod<[TableId, Array<OrderItem>, string], OrderId>,
  'createTable' : ActorMethod<[TableInput], TableId>,
  'createTenant' : ActorMethod<[TenantInput], bigint>,
  'deleteCategory' : ActorMethod<[MenuCategoryId], undefined>,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'deleteTable' : ActorMethod<[TableId], undefined>,
  'deleteTenant' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllTables' : ActorMethod<[], Array<RestaurantTable>>,
  'getAllTenants' : ActorMethod<[], Array<Tenant>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getBillForTable' : ActorMethod<[TableId], [] | [Bill]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategoryId], Array<MenuItem>>,
  'getMyLastReadTimestamp' : ActorMethod<[], Time>,
  'getNewTenantNotifications' : ActorMethod<[Time], Array<TenantNotification>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getOrdersByTable' : ActorMethod<[TableId], Array<Order>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getTableById' : ActorMethod<[TableId], [] | [RestaurantTable]>,
  'getTenantById' : ActorMethod<[bigint], [] | [Tenant]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'markOrderAsPaid' : ActorMethod<[OrderId], undefined>,
  'registerTenant' : ActorMethod<[RegisterTenantInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'suspendTenant' : ActorMethod<[bigint], undefined>,
  'updateCategory' : ActorMethod<
    [MenuCategoryId, string, string, bigint],
    undefined
  >,
  'updateMenuItem' : ActorMethod<
    [
      MenuItemId,
      bigint,
      string,
      string,
      Price,
      [] | [ExternalBlob],
      boolean,
      boolean,
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateTable' : ActorMethod<[TableId, TableInput], undefined>,
  'updateTableStatus' : ActorMethod<[TableId, TableStatus], undefined>,
  'updateTenant' : ActorMethod<[bigint, TenantInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];