/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MenuCategoryId = IDL.Nat;
export const Price = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MenuItemId = IDL.Nat;
export const TableId = IDL.Nat;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : Price,
  'menuItemId' : MenuItemId,
});
export const OrderId = IDL.Nat;
export const TableInput = IDL.Record({
  'name' : IDL.Text,
  'capacity' : IDL.Nat,
  'qrCode' : IDL.Text,
});
export const TenantStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const TenantPlan = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
});
export const TenantInput = IDL.Record({
  'status' : TenantStatus,
  'country' : IDL.Text,
  'outletCount' : IDL.Nat,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'plan' : TenantPlan,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyRevenue' : IDL.Nat,
});
export const MenuCategory = IDL.Record({
  'id' : MenuCategoryId,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'categoryId' : MenuCategoryId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'isVeg' : IDL.Bool,
  'price' : Price,
});
export const TableStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
});
export const RestaurantTable = IDL.Record({
  'id' : TableId,
  'status' : TableStatus,
  'name' : IDL.Text,
  'currentOrderId' : IDL.Opt(OrderId),
  'capacity' : IDL.Nat,
  'qrCode' : IDL.Text,
});
export const Time = IDL.Int;
export const Tenant = IDL.Record({
  'id' : IDL.Nat,
  'status' : TenantStatus,
  'country' : IDL.Text,
  'outletCount' : IDL.Nat,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'plan' : TenantPlan,
  'joinedAt' : Time,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyRevenue' : IDL.Nat,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'actorPrincipal' : IDL.Principal,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'served' : IDL.Null,
  'ready' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'staffId' : IDL.Principal,
  'createdAt' : Time,
  'tableId' : TableId,
  'updatedAt' : Time,
  'totalAmount' : Price,
  'notes' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Bill = IDL.Record({
  'tax' : Price,
  'order' : Order,
  'grandTotal' : Price,
  'subtotal' : Price,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const TenantNotification = IDL.Record({
  'unread' : IDL.Bool,
  'tenant' : Tenant,
});
export const PlatformStats = IDL.Record({
  'suspendedTenants' : IDL.Nat,
  'totalMonthlyRevenue' : IDL.Nat,
  'totalTenants' : IDL.Nat,
  'activeTenants' : IDL.Nat,
  'trialTenants' : IDL.Nat,
});
export const RegisterTenantInput = IDL.Record({
  'country' : IDL.Text,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateTenant' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [MenuCategoryId],
      [],
    ),
  'createMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Price,
        IDL.Opt(ExternalBlob),
        IDL.Bool,
        IDL.Bool,
      ],
      [MenuItemId],
      [],
    ),
  'createOrder' : IDL.Func(
      [TableId, IDL.Vec(OrderItem), IDL.Text],
      [OrderId],
      [],
    ),
  'createTable' : IDL.Func([TableInput], [TableId], []),
  'createTenant' : IDL.Func([TenantInput], [IDL.Nat], []),
  'deleteCategory' : IDL.Func([MenuCategoryId], [], []),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'deleteTable' : IDL.Func([TableId], [], []),
  'deleteTenant' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllTables' : IDL.Func([], [IDL.Vec(RestaurantTable)], ['query']),
  'getAllTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getBillForTable' : IDL.Func([TableId], [IDL.Opt(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategoryId],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getMyLastReadTimestamp' : IDL.Func([], [Time], ['query']),
  'getNewTenantNotifications' : IDL.Func(
      [Time],
      [IDL.Vec(TenantNotification)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getOrdersByTable' : IDL.Func([TableId], [IDL.Vec(Order)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getTableById' : IDL.Func([TableId], [IDL.Opt(RestaurantTable)], ['query']),
  'getTenantById' : IDL.Func([IDL.Nat], [IDL.Opt(Tenant)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationsRead' : IDL.Func([], [], []),
  'markOrderAsPaid' : IDL.Func([OrderId], [], []),
  'registerTenant' : IDL.Func([RegisterTenantInput], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'suspendTenant' : IDL.Func([IDL.Nat], [], []),
  'updateCategory' : IDL.Func(
      [MenuCategoryId, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [
        MenuItemId,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Price,
        IDL.Opt(ExternalBlob),
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateTable' : IDL.Func([TableId, TableInput], [], []),
  'updateTableStatus' : IDL.Func([TableId, TableStatus], [], []),
  'updateTenant' : IDL.Func([IDL.Nat, TenantInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MenuCategoryId = IDL.Nat;
  const Price = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MenuItemId = IDL.Nat;
  const TableId = IDL.Nat;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : Price,
    'menuItemId' : MenuItemId,
  });
  const OrderId = IDL.Nat;
  const TableInput = IDL.Record({
    'name' : IDL.Text,
    'capacity' : IDL.Nat,
    'qrCode' : IDL.Text,
  });
  const TenantStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const TenantPlan = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
  });
  const TenantInput = IDL.Record({
    'status' : TenantStatus,
    'country' : IDL.Text,
    'outletCount' : IDL.Nat,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'plan' : TenantPlan,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyRevenue' : IDL.Nat,
  });
  const MenuCategory = IDL.Record({
    'id' : MenuCategoryId,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'categoryId' : MenuCategoryId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'isVeg' : IDL.Bool,
    'price' : Price,
  });
  const TableStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
  });
  const RestaurantTable = IDL.Record({
    'id' : TableId,
    'status' : TableStatus,
    'name' : IDL.Text,
    'currentOrderId' : IDL.Opt(OrderId),
    'capacity' : IDL.Nat,
    'qrCode' : IDL.Text,
  });
  const Time = IDL.Int;
  const Tenant = IDL.Record({
    'id' : IDL.Nat,
    'status' : TenantStatus,
    'country' : IDL.Text,
    'outletCount' : IDL.Nat,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'plan' : TenantPlan,
    'joinedAt' : Time,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyRevenue' : IDL.Nat,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'actorPrincipal' : IDL.Principal,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'served' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'staffId' : IDL.Principal,
    'createdAt' : Time,
    'tableId' : TableId,
    'updatedAt' : Time,
    'totalAmount' : Price,
    'notes' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Bill = IDL.Record({
    'tax' : Price,
    'order' : Order,
    'grandTotal' : Price,
    'subtotal' : Price,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const TenantNotification = IDL.Record({
    'unread' : IDL.Bool,
    'tenant' : Tenant,
  });
  const PlatformStats = IDL.Record({
    'suspendedTenants' : IDL.Nat,
    'totalMonthlyRevenue' : IDL.Nat,
    'totalTenants' : IDL.Nat,
    'activeTenants' : IDL.Nat,
    'trialTenants' : IDL.Nat,
  });
  const RegisterTenantInput = IDL.Record({
    'country' : IDL.Text,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateTenant' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [MenuCategoryId],
        [],
      ),
    'createMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Price,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
          IDL.Bool,
        ],
        [MenuItemId],
        [],
      ),
    'createOrder' : IDL.Func(
        [TableId, IDL.Vec(OrderItem), IDL.Text],
        [OrderId],
        [],
      ),
    'createTable' : IDL.Func([TableInput], [TableId], []),
    'createTenant' : IDL.Func([TenantInput], [IDL.Nat], []),
    'deleteCategory' : IDL.Func([MenuCategoryId], [], []),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'deleteTable' : IDL.Func([TableId], [], []),
    'deleteTenant' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllTables' : IDL.Func([], [IDL.Vec(RestaurantTable)], ['query']),
    'getAllTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getBillForTable' : IDL.Func([TableId], [IDL.Opt(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategoryId],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getMyLastReadTimestamp' : IDL.Func([], [Time], ['query']),
    'getNewTenantNotifications' : IDL.Func(
        [Time],
        [IDL.Vec(TenantNotification)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getOrdersByTable' : IDL.Func([TableId], [IDL.Vec(Order)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getTableById' : IDL.Func([TableId], [IDL.Opt(RestaurantTable)], ['query']),
    'getTenantById' : IDL.Func([IDL.Nat], [IDL.Opt(Tenant)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationsRead' : IDL.Func([], [], []),
    'markOrderAsPaid' : IDL.Func([OrderId], [], []),
    'registerTenant' : IDL.Func([RegisterTenantInput], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'suspendTenant' : IDL.Func([IDL.Nat], [], []),
    'updateCategory' : IDL.Func(
        [MenuCategoryId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [
          MenuItemId,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Price,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateTable' : IDL.Func([TableId, TableInput], [], []),
    'updateTableStatus' : IDL.Func([TableId, TableStatus], [], []),
    'updateTenant' : IDL.Func([IDL.Nat, TenantInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };