/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AuditLog {
    id: bigint;
    action: string;
    description: string;
    timestamp: Time;
    actorPrincipal: Principal;
}
export type Time = bigint;
export interface Tenant {
    id: bigint;
    status: TenantStatus;
    country: string;
    outletCount: bigint;
    ownerName: string;
    city: string;
    plan: TenantPlan;
    joinedAt: Time;
    businessName: string;
    email: string;
    phone: string;
    monthlyRevenue: bigint;
}
export interface TenantInput {
    status: TenantStatus;
    country: string;
    outletCount: bigint;
    ownerName: string;
    city: string;
    plan: TenantPlan;
    businessName: string;
    email: string;
    phone: string;
    monthlyRevenue: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RestaurantTable {
    id: TableId;
    status: TableStatus;
    name: string;
    currentOrderId?: OrderId;
    capacity: bigint;
    qrCode: string;
}
export interface OrderItem {
    name: string;
    notes: string;
    quantity: bigint;
    price: Price;
    menuItemId: MenuItemId;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type MenuItemId = bigint;
export interface TenantNotification {
    unread: boolean;
    tenant: Tenant;
}
export interface TableInput {
    name: string;
    capacity: bigint;
    qrCode: string;
}
export interface PlatformStats {
    suspendedTenants: bigint;
    totalMonthlyRevenue: bigint;
    totalTenants: bigint;
    activeTenants: bigint;
    trialTenants: bigint;
}
export interface MenuCategory {
    id: MenuCategoryId;
    sortOrder: bigint;
    name: string;
    description: string;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    staffId: Principal;
    createdAt: Time;
    tableId: TableId;
    updatedAt: Time;
    totalAmount: Price;
    notes: string;
    items: Array<OrderItem>;
}
export type Price = bigint;
export interface MenuItem {
    id: MenuItemId;
    categoryId: MenuCategoryId;
    name: string;
    isAvailable: boolean;
    description: string;
    image?: ExternalBlob;
    isVeg: boolean;
    price: Price;
}
export type MenuCategoryId = bigint;
export interface Bill {
    tax: Price;
    order: Order;
    grandTotal: Price;
    subtotal: Price;
}
export interface RegisterTenantInput {
    country: string;
    ownerName: string;
    city: string;
    businessName: string;
    email: string;
    phone: string;
}
export type TableId = bigint;
export type OrderId = bigint;
export interface UserProfile {
    name: string;
    role: string;
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    served = "served",
    ready = "ready"
}
export enum TableStatus {
    occupied = "occupied",
    reserved = "reserved",
    available = "available"
}
export enum TenantPlan {
    pro = "pro",
    enterprise = "enterprise",
    starter = "starter"
}
export enum TenantStatus {
    trial = "trial",
    active = "active",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateTenant(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCategory(name: string, description: string, sortOrder: bigint): Promise<MenuCategoryId>;
    createMenuItem(categoryId: bigint, name: string, description: string, price: Price, image: ExternalBlob | null, isAvailable: boolean, isVeg: boolean): Promise<MenuItemId>;
    createOrder(tableId: TableId, _items: Array<OrderItem>, notes: string): Promise<OrderId>;
    createTable(input: TableInput): Promise<TableId>;
    createTenant(input: TenantInput): Promise<bigint>;
    deleteCategory(id: MenuCategoryId): Promise<void>;
    deleteMenuItem(id: MenuItemId): Promise<void>;
    deleteTable(id: TableId): Promise<void>;
    deleteTenant(id: bigint): Promise<void>;
    getAllCategories(): Promise<Array<MenuCategory>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllTables(): Promise<Array<RestaurantTable>>;
    getAllTenants(): Promise<Array<Tenant>>;
    getAuditLogs(): Promise<Array<AuditLog>>;
    getBillForTable(tableId: TableId): Promise<Bill | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMenuItemsByCategory(categoryId: MenuCategoryId): Promise<Array<MenuItem>>;
    getMyLastReadTimestamp(): Promise<Time>;
    getNewTenantNotifications(lastSeenTimestamp: Time): Promise<Array<TenantNotification>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getOrdersByTable(tableId: TableId): Promise<Array<Order>>;
    getPlatformStats(): Promise<PlatformStats>;
    getTableById(id: TableId): Promise<RestaurantTable | null>;
    getTenantById(id: bigint): Promise<Tenant | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationsRead(): Promise<void>;
    markOrderAsPaid(orderId: OrderId): Promise<void>;
    registerTenant(input: RegisterTenantInput): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    suspendTenant(id: bigint): Promise<void>;
    updateCategory(id: MenuCategoryId, name: string, description: string, sortOrder: bigint): Promise<void>;
    updateMenuItem(id: MenuItemId, categoryId: bigint, name: string, description: string, price: Price, image: ExternalBlob | null, isAvailable: boolean, isVeg: boolean): Promise<void>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
    updateTable(id: TableId, input: TableInput): Promise<void>;
    updateTableStatus(id: TableId, status: TableStatus): Promise<void>;
    updateTenant(id: bigint, input: TenantInput): Promise<void>;
}
import type { Bill as _Bill, ExternalBlob as _ExternalBlob, MenuCategoryId as _MenuCategoryId, MenuItem as _MenuItem, MenuItemId as _MenuItemId, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Price as _Price, RestaurantTable as _RestaurantTable, TableId as _TableId, TableStatus as _TableStatus, Tenant as _Tenant, TenantInput as _TenantInput, TenantNotification as _TenantNotification, TenantPlan as _TenantPlan, TenantStatus as _TenantStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateTenant(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateTenant(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCategory(arg0: string, arg1: string, arg2: bigint): Promise<MenuCategoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async createMenuItem(arg0: bigint, arg1: string, arg2: string, arg3: Price, arg4: ExternalBlob | null, arg5: boolean, arg6: boolean): Promise<MenuItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuItem(arg0, arg1, arg2, arg3, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuItem(arg0, arg1, arg2, arg3, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createOrder(arg0: TableId, arg1: Array<OrderItem>, arg2: string): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async createTable(arg0: TableInput): Promise<TableId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTable(arg0);
            return result;
        }
    }
    async createTenant(arg0: TenantInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTenant(to_candid_TenantInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTenant(to_candid_TenantInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCategory(arg0: MenuCategoryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: MenuItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteTable(arg0: TableId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTable(arg0);
            return result;
        }
    }
    async deleteTenant(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTenant(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<MenuCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTables(): Promise<Array<RestaurantTable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTables();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTables();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTenants(): Promise<Array<Tenant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTenants();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTenants();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs();
            return result;
        }
    }
    async getBillForTable(arg0: TableId): Promise<Bill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillForTable(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillForTable(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: MenuCategoryId): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLastReadTimestamp(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLastReadTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLastReadTimestamp();
            return result;
        }
    }
    async getNewTenantNotifications(arg0: Time): Promise<Array<TenantNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewTenantNotifications(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewTenantNotifications(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByTable(arg0: TableId): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByTable(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByTable(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getTableById(arg0: TableId): Promise<RestaurantTable | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTableById(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTableById(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTenantById(arg0: bigint): Promise<Tenant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTenantById(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTenantById(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async markOrderAsPaid(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderAsPaid(arg0);
            return result;
        }
    }
    async registerTenant(arg0: RegisterTenantInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTenant(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async suspendTenant(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendTenant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendTenant(arg0);
            return result;
        }
    }
    async updateCategory(arg0: MenuCategoryId, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: bigint, arg2: string, arg3: string, arg4: Price, arg5: ExternalBlob | null, arg6: boolean, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTable(arg0: TableId, arg1: TableInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTable(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTable(arg0, arg1);
            return result;
        }
    }
    async updateTableStatus(arg0: TableId, arg1: TableStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTableStatus(arg0, to_candid_TableStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTableStatus(arg0, to_candid_TableStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTenant(arg0: bigint, arg1: TenantInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTenant(arg0, to_candid_TenantInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTenant(arg0, to_candid_TenantInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Bill_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MenuItem_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): Promise<MenuItem> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantTable_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantTable): RestaurantTable {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TableStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TableStatus): TableStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TenantNotification_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TenantNotification): TenantNotification {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_TenantPlan_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TenantPlan): TenantPlan {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TenantStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TenantStatus): TenantStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Tenant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tenant): Tenant {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderId]): OrderId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bill]): Bill | null {
    return value.length === 0 ? null : from_candid_Bill_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantTable]): RestaurantTable | null {
    return value.length === 0 ? null : from_candid_RestaurantTable_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tenant]): Tenant | null {
    return value.length === 0 ? null : from_candid_Tenant_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    categoryId: _MenuCategoryId;
    name: string;
    isAvailable: boolean;
    description: string;
    image: [] | [_ExternalBlob];
    isVeg: boolean;
    price: _Price;
}): Promise<{
    id: MenuItemId;
    categoryId: MenuCategoryId;
    name: string;
    isAvailable: boolean;
    description: string;
    image?: ExternalBlob;
    isVeg: boolean;
    price: Price;
}> {
    return {
        id: value.id,
        categoryId: value.categoryId,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.image)),
        isVeg: value.isVeg,
        price: value.price
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TableId;
    status: _TableStatus;
    name: string;
    currentOrderId: [] | [_OrderId];
    capacity: bigint;
    qrCode: string;
}): {
    id: TableId;
    status: TableStatus;
    name: string;
    currentOrderId?: OrderId;
    capacity: bigint;
    qrCode: string;
} {
    return {
        id: value.id,
        status: from_candid_TableStatus_n26(_uploadFile, _downloadFile, value.status),
        name: value.name,
        currentOrderId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.currentOrderId)),
        capacity: value.capacity,
        qrCode: value.qrCode
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TenantStatus;
    country: string;
    outletCount: bigint;
    ownerName: string;
    city: string;
    plan: _TenantPlan;
    joinedAt: _Time;
    businessName: string;
    email: string;
    phone: string;
    monthlyRevenue: bigint;
}): {
    id: bigint;
    status: TenantStatus;
    country: string;
    outletCount: bigint;
    ownerName: string;
    city: string;
    plan: TenantPlan;
    joinedAt: Time;
    businessName: string;
    email: string;
    phone: string;
    monthlyRevenue: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TenantStatus_n32(_uploadFile, _downloadFile, value.status),
        country: value.country,
        outletCount: value.outletCount,
        ownerName: value.ownerName,
        city: value.city,
        plan: from_candid_TenantPlan_n34(_uploadFile, _downloadFile, value.plan),
        joinedAt: value.joinedAt,
        businessName: value.businessName,
        email: value.email,
        phone: value.phone,
        monthlyRevenue: value.monthlyRevenue
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: _Price;
    order: _Order;
    grandTotal: _Price;
    subtotal: _Price;
}): {
    tax: Price;
    order: Order;
    grandTotal: Price;
    subtotal: Price;
} {
    return {
        tax: value.tax,
        order: from_candid_Order_n39(_uploadFile, _downloadFile, value.order),
        grandTotal: value.grandTotal,
        subtotal: value.subtotal
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    staffId: Principal;
    createdAt: _Time;
    tableId: _TableId;
    updatedAt: _Time;
    totalAmount: _Price;
    notes: string;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    staffId: Principal;
    createdAt: Time;
    tableId: TableId;
    updatedAt: Time;
    totalAmount: Price;
    notes: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n41(_uploadFile, _downloadFile, value.status),
        staffId: value.staffId,
        createdAt: value.createdAt,
        tableId: value.tableId,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        notes: value.notes,
        items: value.items
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unread: boolean;
    tenant: _Tenant;
}): {
    unread: boolean;
    tenant: Tenant;
} {
    return {
        unread: value.unread,
        tenant: from_candid_Tenant_n30(_uploadFile, _downloadFile, value.tenant)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    reserved: null;
} | {
    available: null;
}): TableStatus {
    return "occupied" in value ? TableStatus.occupied : "reserved" in value ? TableStatus.reserved : "available" in value ? TableStatus.available : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    active: null;
} | {
    suspended: null;
}): TenantStatus {
    return "trial" in value ? TenantStatus.trial : "active" in value ? TenantStatus.active : "suspended" in value ? TenantStatus.suspended : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    enterprise: null;
} | {
    starter: null;
}): TenantPlan {
    return "pro" in value ? TenantPlan.pro : "enterprise" in value ? TenantPlan.enterprise : "starter" in value ? TenantPlan.starter : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    served: null;
} | {
    ready: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "served" in value ? OrderStatus.served : "ready" in value ? OrderStatus.ready : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Promise<Array<MenuItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MenuItem_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantTable>): Array<RestaurantTable> {
    return value.map((x)=>from_candid_RestaurantTable_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tenant>): Array<Tenant> {
    return value.map((x)=>from_candid_Tenant_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TenantNotification>): Array<TenantNotification> {
    return value.map((x)=>from_candid_TenantNotification_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n39(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_TableStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): _TableStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_TenantInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantInput): _TenantInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TenantPlan_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantPlan): _TenantPlan {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TenantStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantStatus): _TenantStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TenantStatus;
    country: string;
    outletCount: bigint;
    ownerName: string;
    city: string;
    plan: TenantPlan;
    businessName: string;
    email: string;
    phone: string;
    monthlyRevenue: bigint;
}): {
    status: _TenantStatus;
    country: string;
    outletCount: bigint;
    ownerName: string;
    city: string;
    plan: _TenantPlan;
    businessName: string;
    email: string;
    phone: string;
    monthlyRevenue: bigint;
} {
    return {
        status: to_candid_TenantStatus_n14(_uploadFile, _downloadFile, value.status),
        country: value.country,
        outletCount: value.outletCount,
        ownerName: value.ownerName,
        city: value.city,
        plan: to_candid_TenantPlan_n16(_uploadFile, _downloadFile, value.plan),
        businessName: value.businessName,
        email: value.email,
        phone: value.phone,
        monthlyRevenue: value.monthlyRevenue
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantStatus): {
    trial: null;
} | {
    active: null;
} | {
    suspended: null;
} {
    return value == TenantStatus.trial ? {
        trial: null
    } : value == TenantStatus.active ? {
        active: null
    } : value == TenantStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantPlan): {
    pro: null;
} | {
    enterprise: null;
} | {
    starter: null;
} {
    return value == TenantPlan.pro ? {
        pro: null
    } : value == TenantPlan.enterprise ? {
        enterprise: null
    } : value == TenantPlan.starter ? {
        starter: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    served: null;
} | {
    ready: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.served ? {
        served: null
    } : value == OrderStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): {
    occupied: null;
} | {
    reserved: null;
} | {
    available: null;
} {
    return value == TableStatus.occupied ? {
        occupied: null
    } : value == TableStatus.reserved ? {
        reserved: null
    } : value == TableStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
